"""
ClickUp Integration Skill

Provides UI interface and notifications via ClickUp (free tier).
- Create tasks for each recommendation
- Update task status as recommendations progress
- Send daily summaries as task comments
- Dashboard view of all active recommendations

Setup:
1. Create ClickUp account at https://clickup.com (free tier)
2. Create a List for investment recommendations
3. Get API key from Settings → Apps → API
4. Set env vars: CLICKUP_API_KEY, CLICKUP_LIST_ID
"""

import os
import json
import requests
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).parent.parent

CLICKUP_API_BASE = "https://api.clickup.com/api/v2"

def get_headers():
    """Get ClickUp API headers."""
    api_key = os.environ.get("CLICKUP_API_KEY", "")
    if not api_key:
        return None
    return {
        "Authorization": api_key,
        "Content-Type": "application/json"
    }

def create_recommendation_task(recommendation: dict) -> dict:
    """
    Create a ClickUp task for a new recommendation.
    
    Args:
        recommendation: {
            "ticker": "AAPL",
            "action": "BUY",
            "thesis": "...",
            "entry_price": 150.00,
            "target_price": 200.00,
            "stop_loss": 130.00,
            "conviction": 8,
            "horizon": "3-12 months"
        }
    
    Returns:
        Task details or error
    """
    headers = get_headers()
    if not headers:
        return {"error": "ClickUp not configured. Set CLICKUP_API_KEY env var."}
    
    list_id = os.environ.get("CLICKUP_LIST_ID", "")
    if not list_id:
        return {"error": "ClickUp list ID not set. Set CLICKUP_LIST_ID env var."}
    
    # Format task title
    title = f"{recommendation.get('action', 'BUY')} {recommendation.get('ticker', 'N/A')} - Conviction {recommendation.get('conviction', 'N/A')}/10"
    
    # Format task description
    description = f"""
## Investment Recommendation

**Ticker:** {recommendation.get('ticker', 'N/A')}
**Action:** {recommendation.get('action', 'N/A')}
**Conviction:** {recommendation.get('conviction', 'N/A')}/10
**Horizon:** {recommendation.get('horizon', 'N/A')}

### Thesis
{recommendation.get('thesis', 'N/A')}

### Price Levels
- **Entry:** ${recommendation.get('entry_price', 'N/A')}
- **Target:** ${recommendation.get('target_price', 'N/A')}
- **Stop Loss:** ${recommendation.get('stop_loss', 'N/A')}

### Status
- **Created:** {datetime.now().strftime('%Y-%m-%d %H:%M')}
- **Status:** Active
- **Outcome:** Pending

---
*Auto-generated by Kaizen Quest Agent*
"""
    
    task_data = {
        "name": title,
        "description": description,
        "status": "Active",
        "priority": _conviction_to_priority(recommendation.get('conviction', 5)),
        "due_date": None  # No due date for long-term investments
    }
    
    try:
        response = requests.post(
            f"{CLICKUP_API_BASE}/list/{list_id}/task",
            headers=headers,
            json=task_data,
            timeout=10
        )
        
        if response.status_code == 200:
            task = response.json()
            return {
                "task_id": task["id"],
                "name": task["name"],
                "url": task.get("url", ""),
                "status": "created"
            }
        else:
            return {"error": f"ClickUp API error: {response.status_code} - {response.text}"}
    except Exception as e:
        return {"error": str(e)}

def update_task_status(task_id: str, status: str, comment: str = None) -> dict:
    """
    Update a recommendation task status.
    
    Status options: Active, Target Hit, Stop Loss, Expired, Closed
    """
    headers = get_headers()
    if not headers:
        return {"error": "ClickUp not configured"}
    
    try:
        # Update status
        response = requests.put(
            f"{CLICKUP_API_BASE}/task/{task_id}",
            headers=headers,
            json={"status": status},
            timeout=10
        )
        
        # Add comment if provided
        if comment:
            requests.post(
                f"{CLICKUP_API_BASE}/task/{task_id}/comment",
                headers=headers,
                json={"comment_text": comment},
                timeout=10
            )
        
        return {"status": "updated", "task_id": task_id, "new_status": status}
    except Exception as e:
        return {"error": str(e)}

def send_daily_summary(summary: str) -> dict:
    """
    Send daily summary as a comment on a summary task.
    Creates a new task for each day's summary.
    """
    headers = get_headers()
    if not headers:
        return {"error": "ClickUp not configured"}
    
    list_id = os.environ.get("CLICKUP_LIST_ID", "")
    
    task_data = {
        "name": f"📊 Daily Summary - {datetime.now().strftime('%Y-%m-%d')}",
        "description": summary,
        "status": "Completed",
        "priority": 3
    }
    
    try:
        response = requests.post(
            f"{CLICKUP_API_BASE}/list/{list_id}/task",
            headers=headers,
            json=task_data,
            timeout=10
        )
        
        if response.status_code == 200:
            return {"status": "sent", "task_id": response.json()["id"]}
        else:
            return {"error": f"ClickUp API error: {response.status_code}"}
    except Exception as e:
        return {"error": str(e)}

def get_active_recommendations() -> list:
    """Get all active recommendation tasks from ClickUp."""
    headers = get_headers()
    if not headers:
        return []
    
    list_id = os.environ.get("CLICKUP_LIST_ID", "")
    
    try:
        response = requests.get(
            f"{CLICKUP_API_BASE}/list/{list_id}/task?statuses[]=Active&statuses[]=Target Hit",
            headers=headers,
            timeout=10
        )
        
        if response.status_code == 200:
            tasks = response.json().get("tasks", [])
            return [{
                "id": t["id"],
                "name": t["name"],
                "status": t["status"]["status"],
                "url": t.get("url", "")
            } for t in tasks]
        else:
            return []
    except Exception:
        return []

def _conviction_to_priority(conviction: int) -> int:
    """Convert conviction score (1-10) to ClickUp priority (1-4)."""
    if conviction >= 9:
        return 1  # Urgent
    elif conviction >= 7:
        return 2  # High
    elif conviction >= 5:
        return 3  # Normal
    else:
        return 4  # Low

__all__ = [
    'create_recommendation_task',
    'update_task_status',
    'send_daily_summary',
    'get_active_recommendations'
]